---
title: 'Data Wrangling Shiny App'
author: "Muhammad Ahsan Tahir"
date: "March 21, 2023"

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small",   # slightly smaller font for code
  message=FALSE)  # suppress non-warning messages

# load packages
library(tidyverse)
library(rvest)
library(kableExtra)
load("LauwrangledData.RData")
```

```{r}
theURLPart1 <- "https://fbref.com/en/comps/9/"
theURLPart2 <- "-Premier-League-Stats"
```



```{r, eval = FALSE}
robotstxt::paths_allowed("https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats")
```



> I swear I will make my code look prettier once we make the app. :-)

```{r}
tables <- list()
for (season in seq(from = 2013, to = 2022, by = 1)) {
  tables[[season]] <- paste(theURLPart1, toString(season-1), "-",
                            toString(season), "/",  toString(season-1), "-",
                            toString(season), theURLPart2, sep = "") %>%
    read_html() %>% 
  html_nodes("table")%>%
  purrr::pluck(1) %>%
  html_table() %>%
  select(1:10)
    
}
tables <- tables[-c(1:2012)]
names(tables) <- c("2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022")
tables
```

```{r}
library(dplyr)

# Merge the tables and add a column with their corresponding year
attacking_table <- bind_rows(tables, .id = "Year")

# Convert the Year column to integer
attacking_table$Year <- as.integer(attacking_table$Year)

# Save the merged table
save(attacking_table, file = "MuhammadAhsanTahir.RData")
```




